export const MUNICIPIOS_BY_PROVINCIAS = {
	"Pinar del Rio": [
		"Pinar del Río",
		"Consolación del Sur",
		"Guane",
		"San Juan y Martínez",
		"San Luis",
		"Viñales",
		"Los Palacios",
		"Mantua",
	],
	Artemisa: [
		"Artemisa",
		"Guanajay",
		"San Cristóbal",
		"Bahía Honda",
		"Candelaria",
		"Mariel",
		"Caimito",
		"Bauta",
		"San Antonio de los Baños",
		"Güira de Melena",
		"Alquízar",
		"Guira de Melena",
		"San Antonio de los Baños",
	],
	"La Habana": [
		"Habana Vieja",
		"Centro Habana",
		"Plaza de la Revolución",
		"Cerro",
		"Diez de Octubre",
		"La Lisa",
		"Marianao",
		"Playa",
		"Guanabacoa",
		"Regla",
		"San Miguel del Padrón",
		"Cotorro",
		"Boyeros",
		"Arroyo Naranjo",
	],
	Mayabeque: [
		"San José de las Lajas",
		"Batabanó",
		"Güines",
		"Melena del Sur",
		"Bejucal",
		"Quivicán",
		"Nueva Paz",
		"Madruga",
		"Jaruco",
		"Santa Cruz del Norte",
	],
	Matanzas: [
		"Matanzas",
		"Cárdenas",
		"Varadero",
		"Jovellanos",
		"Pedro Betancourt",
		"Perico",
		"Colón",
		"Limonar",
		"Martí",
		"Calimete",
		"Jagüey Grande",
		"Los Arabos",
		"Unión de Reyes",
	],
	Cienfuegos: [
		"Cienfuegos",
		"Palmira",
		"Rodas",
		"Abreus",
		"Cumanayagua",
		"Cruces",
	],
	"Villa Clara": [
		"Santa Clara",
		"Sagua la Grande",
		"Placetas",
		"Remedios",
		"Caibarién",
		"Camajuaní",
		"Encrucijada",
		"Manicaragua",
		"Corralillo",
	],
	"Sancti Spíritus": [
		"Sancti Spíritus",
		"Trinidad",
		"Cabaiguán",
		"Yaguajay",
		"Jatibonico",
		"Fomento",
		"Taguasco",
		"La Sierpe",
	],
	"Ciego de Ávila": [
		"Ciego de Ávila",
		"Morón",
		"Chambas",
		"Florencia",
		"Majagua",
		"Bolivia",
		"Venezuela",
	],
	Camagüey: [
		"Camagüey",
		"Florida",
		"Nuevitas",
		"Guáimaro",
		"Santa Cruz del Sur",
		"Vertientes",
		"Esmeralda",
		"Sibanicú",
		"Minas",
		"Sierra de Cubitas",
	],
	"Las Tunas": [
		"Las Tunas",
		"Puerto Padre",
		"Manatí",
		"Majibacoa",
		"Jesús Menéndez",
		"Amancio",
	],
	Holguín: [
		"Holguín",
		"Moa",
		"Sagua de Tánamo",
		"Banes",
		"Gibara",
		"Rafael Freyre",
		"Antilla",
		"Calixto García",
		"Cacocum",
		"Frank País",
		"Urbano Noris",
	],
	Granma: [
		"Bayamo",
		"Manzanillo",
		"Niquero",
		"Jiguaní",
		"Yara",
		"Río Cauto",
		"Bartolomé Masó",
		"Pilón",
	],
	"Santiago de Cuba": [
		"Santiago de Cuba",
		"Palma Soriano",
		"Contramaestre",
		"San Luis",
		"El Cobre",
		"El Cristo",
		"Songo-La Maya",
		"Segundo Frente",
		"Tercer Frente",
		"Guamá",
	],
	Guantánamo: [
		"Guantánamo",
		"Baracoa",
		"Maisí",
		"Imías",
		"Yateras",
		"San Antonio del Sur",
		"Caimanera",
		"Niceto Pérez",
		"El Salvador",
	],
	"Isla de la Juventud": [
		"Nueva Gerona",
		"La Fe",
		"Los Palacios",
		"Santa Fe",
		"Isla de la Juventud",
	],
};

export const PROVINCIAS = Object.keys(MUNICIPIOS_BY_PROVINCIAS);
