// Generated by https://quicktype.io

export interface UserDB {
    id:        string;
    username:  string;
    lastName:  string;
    password:  string;
    email:     string;
    role:      string[];
    organismo: string;
    address:   string;
    isDeleted: boolean;
}
